sudo: false
language: go
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.tar.gz | tar xvz
script:
  - echo 'generate contents'
  - ./hugo
after_success:
- ./deploy.py
env:
  global:
  - secure: "AB11xzA9aluJBHsqVcIPRyKcs56ipA36jEGe+NqODCqrgnwSwPFQWUM7/46hPegzugklJQEHSvWF9R1VLYd10cULGh2mAJS/LZDgbWwXiJzpPtV7PFOzTSKpcW41llQ6qnepkfbdvbVmhTwmRBzAwJBm7x/zCYwNlv5qbdwx+ChTkDOnHFu8NsS7mmUSjX4mCRpv9qweLL9VkUvoTf+yPuoqqXRXJiX11+vtxHzbaANuEf4ncSx7qyZDwz6uAJ3nmCFDvH8uebtyWHR7KeWu7VwOhjSMo10ei/vbe4MV4jA2IjQo/4hXYbrG26JR97m84IhY4UjV+hbZIa8Oorqeh7Y+sNpx4SCpdpuk6cMWCYko4BywQoic9e/m4QsTRjr/Bp5NN0gYLFkNZbkrmwIFdvP0STyb4mmptJ/RZzJecceMi093JtRvIXvKvXstcK8x/n6VgTtvF60f1tJeN9D/SoWwj86C2mVVpHVoQKS09NMXQ9Oycwl+Ait27bNb0Jb3wRbCpQYKnvctMj1XuTxZsp4ww/zbSaKpvlh+7QwueZXZXTKgKd9rv67ZB67iK8HngA1+rYxyZo3kv3E1x5b5uxzKtFRp4q/IdivY7M0TC7M9Hei/kut1BHlIWOt7NTcAptXw3dJ3QGFc8FYkHlDhOcwEKfDl6J8kZpJO4IlniFw="
  - USER_NAME: "Weiyuen Wu"
  - USER_EMAIL: "doomsplayer@gmail.com"
