baseurl = "http://wooya.me/"
Title = "IRIS"
copyright = "&copy; 2017 Young"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
hasCJKLanguage = true
footnotereturnlinkcontents = "<sup>^</sup>"
RSSUri = "feed.xml"
metaDataFormat = "yaml"
# Enable comments by entering your Disqus shortname
disqusShortname = "wooyame"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-64002783-1"


[params]
  name = "Young Wu"
  role = "MSc Student"
  organization = "SFU"
  avatar = "me.png"
  email = "doomsplayer@gmail.com"
  address = "8888 University Drirve, Burnaby, BC, V5A 1S6"
  #telegram = "wooya42"
  #phone = "Secret"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:doomsplayer@gmail.com"

  # [[params.social]]
  #   icon = "google-scholar"
  #   icon_pack = "ai"
  #   link = "//scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/doomsplayer"

  [[params.social]]
    icon = "institution"
    icon_pack = "fa"
    link = "//www.sfu.ca"

  [[params.social]]
    icon = "coffee"
    icon_pack = "fa"
    link = "//www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LKM2L7LDMU6ZS"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

# [[menu.main]]
#   name = "Publications"
#   url = "#publications_selected"
#   weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

# [[menu.main]]
#   name = "Teaching"
#   url = "#teaching"
#   weight = 5

[[menu.main]]
  name = "Talk"
  url = "#talks"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[menu.main]]
  name = "RSS"
  weight = 100
  url = "/feed.xml"
  
[[menu.main]]
  name = "Sitemap"
  weight = 101
  url = "/sitemap.xml"


# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"